# These are the required properties but with example values.
# Copy this file to application.properties in this same directory
# then place real values according to your environment.
oci.streaming.endpoint=https://streaming.us-phoenix-1.oci.oraclecloud.com
oci.identity.endpoint=https://identity.us-phoenix-1.oci.oraclecloud.com
oci.streaming.tenancy=ocid1.tenancy.oc1..mytenantocid
oci.streaming.compartment=ocid1.compartment.oc1..mycompartmentocid
oci.auth.profile=DEFAULT

# Kafka-compatible demo settings
oci.kafka.username.base=my-tenancy/my-user
oci.kafka.password=my-auth-token

# Optional if your Kafka endpoint needs an explicit truststore
#oci.kafka.truststore.location=/path/to/truststore.jks
#oci.kafka.truststore.password=changeit
